### YamlMime:Landing
title: Dokumentacja platformy Docker na platformie Azure
summary: Docker to popularna platforma do zarządzania kontenerami i tworzenia ich obrazów, która pozwala szybko pracować z kontenerami w systemach Linux i Windows. Dowiedz się, jak korzystać z platformy Docker na platformie Azure.
metadata:
  title: Dokumentacja platformy Docker na platformie Azure
  description: Docker to popularna platforma do zarządzania kontenerami i tworzenia ich obrazów, która pozwala szybko pracować z kontenerami w systemach Linux i Windows.
  services: multiple
  ms.service: multiple
  ms.topic: landing-page
  author: georgewallace
  ms.author: gwallace
  ms.date: 03/08/2020
  ms.openlocfilehash: 700c5b1e113de32b80b3d716db915836049128ec
  ms.sourcegitcommit: 829d951d5c90442a38012daaf77e86046018e5b9
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 10/09/2020
  ms.locfileid: "89470123"
landingContent:
- title: Wdrażanie platformy Docker na platformie Azure
  linkLists:
  - linkListType: overview
    links:
    - text: Szablon Szybki start dotyczący wdrażania platformy Docker w systemie Ubuntu
      url: https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/
- title: Rozpoczęcie pracy
  linkLists:
  - linkListType: tutorial
    links:
    - text: Uruchamianie aplikacji internetowej Python (Django) z bazą danych PostgreSQL w usłudze Azure App Service
      url: ../app-service/tutorial-python-postgresql-app.md
    - text: Budowanie infrastruktury tworzenia aplikacji na maszynie wirtualnej systemu Linux na platformie Azure przy użyciu usługi Jenkins, GitHub i Docker
      url: /azure/developer/jenkins/pipeline-with-github-and-docker
- title: Zasoby
  linkLists:
  - linkListType: reference
    links:
    - text: Witryna platformy Azure dla platformy Docker
      url: https://docs.docker.com/docker-for-azure/why/
    - text: Sterownik platformy Azure dla platformy Docker
      url: https://docs.docker.com/machine/drivers/azure/
    - text: Informacje na temat platformy Docker
      url: https://docker.com
