- name: Platforma Kubernetes z włączoną usługą Azure Arc
  href: index.yml
- name: Omówienie
  items:
    - name: Informacje na temat platformy Kubernetes z włączoną usługą Azure Arc
      href: overview.md
- name: Samples
  items:
    - name: Elementy wbudowane usługi Azure Policy
      href: ./policy-samples.md
- name: Przewodniki z instrukcjami
  items:
    - name: Operacje klastra
      items:
        - name: Połączenie klastra
          href: connect-cluster.md
        - name: Korzystanie z podejścia GitOps na potrzeby połączonego klastra
          href: use-gitops-connected-cluster.md
        - name: Korzystanie z podejścia GitOps przy użyciu narzędzia Helm
          href: use-gitops-with-helm.md
        - name: Wymuś metodykę GitOps przy użyciu usługi Azure Policy
          href: use-azure-policy.md
        - name: Monitorowanie za pomocą usługi Azure Monitor dla kontenerów
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md
        - name: Zasady kontroli przyjmowania przy użyciu usługi Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Wdrażanie obciążeń IoT
          href: deploy-azure-iot-edge-workloads.md
        - name: Nazwa główna usługi dołączania
          href: create-onboarding-service-principal.md
        - name: Rozwiązywanie problemów
          href: Troubleshooting.md